### ISSUE TITLE
Garder le mot de passe pour un website dans la session de l'utilisateur

### ISSUE THREAD

**Issue by j4kim** [HE-Arc/iziCMS#12]

**Comment by greut** [comment]
:cake: https://docs.djangoproject.com/en/1.10/topics/http/sessions/#examples

**Comment by j4kim** [comment]
https://github.com/HE-Arc/iziCMS/commit/a0e5a1e37f548e840aaab71c531243baa08bcf7a#diff-e6873fc012a7c853c4add77c10590f27R25
(bug incompréhensible avec le token)
