### ISSUE TITLE
parser fichier html et récupréer que le body

### ISSUE THREAD

**Issue by j4kim** [HE-Arc/iziCMS#14]
Avant d'afficher la vue d'édition d'une page, parser le fichier html à éditer et n'intégrer que le contenu de l'élément body dans l'éditeur
voir https://docs.python.org/3/library/html.parser.html

**Comment by greut** [comment]
https://pypi.python.org/pypi/beautifulsoup4

HTML est tout sauf simple à parser. Je ne suis pas sûr que `html` suffise.

**Comment by j4kim** [comment]
Tu peux essayer de faire ça @julien-baumgartner 
https://github.com/HE-Arc/iziCMS/issues/20
