### ISSUE TITLE
Affichage de l'arborescence FTP

### ISSUE THREAD

**Issue by j4kim** [HE-Arc/iziCMS#18]
Ce serait bien, mais c'est chaud.
Il faudrait pouvoir afficher l'arborescence, sélectionner un fichier et en récupérer le chemin.

**Comment by greut** [comment]
Avec le _bookmarklet_, vous vous évitez ceci.

**Comment by j4kim** [comment]
Ok mais on est sûr de faire le lien entre l'url et le fichier à tous les coups ?

**Comment by greut** [comment]
Ne le faites-vous pas déjà dans l'autre sens. Je modifie une page puis peux consulter le résultat sur le vrai site?

**Comment by j4kim** [comment]
ben oui mais c'est l'utilisateur qui doit rentrer le chemin sur le serveur et l'url publique manuellement

**Comment by greut** [comment]
1. `http://monsite.com/prix.html`
2. _bookmarklet_
3. `http://izic.ms/edit/monsite.com/prix.html`
   - demande des informations FTP (plus ou moins sauvegardées dans la DB)
   - recherche magique du fichier `/prix.html` (via `mlsd` ou `nlst`) (avec aide de la DB)
   - affichage de l'éditeur

**Comment by j4kim** [comment]
euh ok...
du coup monsite.com est la clé primaire du site ?
pour l'instant c'est le couple ftp_host/ftp_user mais c'est vrai que ça a pas vraiment de sens...

**Comment by greut** [comment]
le schéma de la db n'est pas forcément reflétée dans l'interface utilisateur.

**Comment by j4kim** [comment]
Ben je vais essayer mais je vois pas trop comment récupérer le modèle du site à partir du bookmarklet
