### ISSUE TITLE
Garder les attributs des éléments dans l'éditeur

### ISSUE THREAD

**Issue by j4kim** [HE-Arc/iziCMS#21]
Je sais pas si c'est possible mais il faudrait garder les attributs des éléments quand on les charge dans Quill.

Du genre un truc comme ça :  
```html
<div id="header">
    <ul class="navbar">...</ul>
</div>
```
va être transformé en :  
```html
<div>
    <ul>...</ul>
</div>
```

C'est nul... ça dénature la page forcément

**Comment by greut** [comment]
Textarea? #8

**Comment by j4kim** [comment]
oui ok mais c'est quoi l'intérêt de notre projet si l'édition se fait dans un textarea ?

**Comment by j4kim** [comment]
On ferait pas mieux d'utiliser `contentEditable` ?

**Comment by greut** [comment]
ça dépend de ce que vous désirez offrir.
