### ISSUE TITLE
learning Quill js

### ISSUE THREAD

**Issue by SylvainRamseyer** [HE-Arc/iziCMS#8]
Prise en main de Quill

**Comment by greut** [comment]
Débutez avec un  `<textarea>`

**Comment by greut** [comment]
Je dis ça car si vous n'avez pas le temps d'apprendre Quill.js vous n'aurez rien. Si vous mettez un `textarea`, vous aurez toujours moyen d'améliorer par la suite.

**Comment by greut** [comment]
>> _"Always implement things when you actually need them, never when you just foresee that you need them."_
>
> Even if you're totally, totally, totally sure that you'll need a feature later on, don't implement it now. Usually, it'll turn out either
>
> a) you don't need it after all, or
> b) what you actually need is quite different from what you foresaw needing earlier. 
>
> http://wiki.c2.com/?YouArentGonnaNeedIt

**Comment by j4kim** [comment]
Oui oui, après, "learn" quill.js c'est un peu fort, ça consiste à faire `var editor = new Quill('#editor')`

**Comment by greut** [comment]
@j4kim yup. Néanmoins, j'insiste.
