### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by SylvainRamseyer** [HE-Arc/iziCMS#9]

**Comment by greut** [comment]
yagni ;-)

**Comment by j4kim** [comment]
Apparemment wagni ouais https://docs.djangoproject.com/fr/1.10/topics/auth/ mais faut quand même le mettre en place

**Comment by j4kim** [comment]
Nouveau système : on authentifie des sites et pas les utilisateurs.
La première partie est faite dans cette issue : https://github.com/HE-Arc/iziCMS/issues/12
C'est à dire la connexion à un site déjà existant, il reste à faire la création : https://github.com/HE-Arc/iziCMS/issues/15
